In [2]:
import numpy as np

In [2]:
fahrenheit = np.array([32, 68, 104,212])
celsius = (fahrenheit - 32) * 5.0 / 9.0
print("Fahreheit values : ",fahrenheit)
print("Celsius values : ",celsius)

Fahreheit values :  [ 32  68 104 212]
Celsius values :  [  0.  20.  40. 100.]


In [3]:
random_array = np.random.rand(1000)

print(f"Average :{np.mean(random_array)}")
print(f"Variance :{np.var(random_array)}")
print(f"Standard Deviation :{np.std(random_array)}")


Average :0.5018719314999026
Variance :0.08166066130841756
Standard Deviation :0.28576329594336913


In [5]:
angles= np.array([12, 30, 45, 60, 90])
radians = angles * (np.pi / 180)
print("Angles in degrees: ", angles)
print("Angles in radians: ", radians)

Angles in degrees:  [12 30 45 60 90]
Angles in radians:  [0.20943951 0.52359878 0.78539816 1.04719755 1.57079633]


In [ ]:
arr = np.array([5, 10, 15, 20, 25])
diff = np.diff(arr)
print("Original array:", arr)
print("Difference between neighbouring elements:", diff)

Original array: [ 5 10 15 20 25]
Difference between neighbouring elements: [5 5 5 5]


In [17]:
arr = np.array([2+3j, 1+2j, 2+1j, 1+1j, 3+5j])

sorted_arr = np.sort_complex(arr)

print("Original array:", arr)
print("Sorted array:", sorted_arr)


Original array: [2.+3.j 1.+2.j 2.+1.j 1.+1.j 3.+5.j]
Sorted array: [1.+1.j 1.+2.j 2.+1.j 2.+3.j 3.+5.j]


In [ ]:
arr = np.random.randint(1, 11, size=6)

greater_than_4 = arr[arr > 4]

print("Original array:", arr)
print("Values greater than 4:", greater_than_4)


Original array: [ 2  7 10  2 10  4]
Values greater than 4: [ 7 10 10]


In [6]:
arr = np.random.randint(0, 21, size=8)
print("Array:", arr)

num = int(input("Enter the number to search for: "))

indices = np.where(arr == num)[0]

if indices.size > 0:
    print(f"Number {num} found at positions: {indices}")
else:
    print(f"Number {num} not found in the array.")

Array: [14  7  9  8 15 19 13  5]
Number 8 found at positions: [3]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.savetxt('array.txt', arr, fmt='%d')
loaded_arr = np.loadtxt('array.txt', dtype=int)

print("Original array:")
print(arr)

print("\nLoaded array:")
print(loaded_arr)

Original array:
[[1 2 3]
 [4 5 6]]

Loaded array:
[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
even_arr = np.arange(30, 61, 2)
print(even_arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [11]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
total_sum = np.sum(arr)
col_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)
print("Array:\n", arr)
print("Sum of all elements:", total_sum)
print("Sum of each column:", col_sum)
print("Sum of each row:", row_sum)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


In [ ]:
mat= np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
mat_transpose = np.transpose(mat)
print("Original matrix:\n", mat)
print("Transposed matrix:\n", mat_transpose)
tra=np.trace(mat)
print("Trace of the matrix:", tra)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Trace of the matrix: 15


In [ ]:
mat1=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mat2=np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

mat_product=np.dot(mat1, mat2)
print("Result of matrix multiplication:\n", mat_product)


Result of matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [14]:
mat3=np.array([[1,2,3],
                [4,8,6],
                [7,8,10]])

mat_inverse=np.linalg.inv(mat3)
print("Inverse of the matrix:\n", mat_inverse)
print("Rank of the matrix:", np.linalg.matrix_rank(mat3))

Inverse of the matrix:
 [[-0.88888889 -0.11111111  0.33333333]
 [-0.05555556  0.30555556 -0.16666667]
 [ 0.66666667 -0.16666667  0.        ]]
Rank of the matrix: 3


In [15]:
mat4= np.array([[1, 2, 3],
                [4, 9, 6],
                [7, 8, 10]])

eigenvalues, eigenvectors = np.linalg.eig(mat4)
print("Eigenvalues of the matrix:\n", eigenvalues)
print("Eigenvectors of the matrix:\n", eigenvectors)

Eigenvalues of the matrix:
 [18.08711725 -0.91794244  2.8308252 ]
Eigenvectors of the matrix:
 [[-0.20593783 -0.84935244  0.21192083]
 [-0.60070671  0.02355406 -0.74851659]
 [-0.77249016  0.52730033  0.62834106]]
