In [10]:
import numpy as np

n=(1, 2, 3, 4, 5)
print(type(n))
n = np.array(n)
print(type(n))
arr=np.arange(2,100,2)
print(arr)

<class 'tuple'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [14]:
print(np.ones((3, 4)))  

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
print(np.identity(3))
print("\n")
print(np.eye(3, 4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [31]:
arr2=np.arange(1, 10)
print(arr2[5:])
print(arr2[3])
a=arr2.copy()
a[2]=10
print(arr2)

[6 7 8 9]
4
[1 2 3 4 5 6 7 8 9]


In [40]:
a=np.ones((3, 5))
b=np.zeros((3, 4))
print(np.concatenate((a, b),axis=1))


[[1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0.]]


In [51]:
k=np.arange(1, 10)
x=np.where(k==20)
if x[0].size == 0:
    print("number not found in the array")
else:
    print(f"number found at position {x[0][0]} in the array")

number not found in the array
